/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mercado.telas;

import com.mycompany.mercado.controle.EventoCliente;
import com.mycompany.mercado.mercadoClasses.Cliente;
import static com.mycompany.mercado.mercadoClasses.Cliente.cliente;
import java.text.ParseException;
import com.mycompany.mercado.mercadoClasses.Pessoa;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;


/**
 *
 * @author gusta
 */
public class cadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form cadastroCliente
     */
    JFrame telaAnterior;
    public cadastroCliente() {
        initComponents();
        this.addWindowListener(new EventoCliente(this));
    }
    public cadastroCliente(JFrame telaAnterior){
        this();
        this.telaAnterior = telaAnterior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textoN = new javax.swing.JTextField();
        textT = new javax.swing.JTextField();
        textE = new javax.swing.JTextField();
        textC = new javax.swing.JTextField();
        try {
            textC = new JFormattedTextField(new MaskFormatter("###.###.###-##"));
        } catch (ParseException e) {}
        jLabel6 = new javax.swing.JLabel();
        textI = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbC = new javax.swing.JTable();
        editaC = new javax.swing.JButton();
        atualizaC = new javax.swing.JButton();
        apagaC = new javax.swing.JButton();
        voltaC = new javax.swing.JButton();
        cadastraC = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Nome", "Telefone", "CPF", "Endereço", "Idade"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Cliente");

        jLabel2.setText("Nome:");

        jLabel3.setText("CPF:");

        jLabel4.setText("Telefone:");

        jLabel5.setText("Endereço:");

        jLabel6.setText("Idade:");

        tbC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Nome", "Telefone", "CPF", "Endereço", "Idade"
            }
        ));
        jScrollPane2.setViewportView(tbC);

        editaC.setText("Editar");
        editaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editaCActionPerformed(evt);
            }
        });

        atualizaC.setText("Atualizar");
        atualizaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaCActionPerformed(evt);
            }
        });

        apagaC.setText("Apagar");
        apagaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagaCActionPerformed(evt);
            }
        });

        voltaC.setText("Voltar");
        voltaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltaCActionPerformed(evt);
            }
        });

        cadastraC.setText("Cadastrar");
        cadastraC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastraCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editaC)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(atualizaC)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(apagaC)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(voltaC))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 46, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(textI))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(textoN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textT, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textE, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cadastraC)
                        .addGap(324, 324, 324))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(textoN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(textE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(cadastraC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editaC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atualizaC)
                    .addComponent(apagaC)
                    .addComponent(voltaC))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(742, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastraCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraCActionPerformed
        if(textoN.getText().equals("") || textC.getText().equals("") || textE.getText().equals("") || textT.getText().equals("") || textI.getText().equals(""))
          JOptionPane.showMessageDialog(null,"Preencha todos os campos.",null,JOptionPane.ERROR_MESSAGE);  
        else{
            String nome = this.textoN.getText().trim();
            String tel = this.textT.getText().trim();
            String end = this.textE.getText().trim();
            String cpf = this.textC.getText().trim();
            String idade = this.textI.getText().trim();
        

            if(Pessoa.verificaContato(tel)==true){
                DefaultTableModel val = (DefaultTableModel) tbC.getModel();
                val.addRow(new String[]{nome, tel, cpf, end, idade});
                
                textoN.setText("");
                textC.setText("");
                textI.setText("");
                textE.setText("");
                textT.setText(""); 
                 
                textoN.requestFocus();
                 
                Cliente cli = new Cliente (nome, cpf, tel, end, idade);
                cliente.add(cli);
            }else{
                JOptionPane.showMessageDialog(null,"Digite apenas números no telefone.",null,JOptionPane.ERROR_MESSAGE);
                textT.setText("");
            
                textT.requestFocus();
            }
        }
    }//GEN-LAST:event_cadastraCActionPerformed

    private void apagaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagaCActionPerformed
        if(tbC.getSelectedRow()== -1)
            JOptionPane.showMessageDialog(null,"Selecione uma linha antes de apagar.",null,JOptionPane.INFORMATION_MESSAGE);
        else{
            if(textoN.getText().equals("") || textT.getText().equals("") || textC.getText().equals("") || textE.getText().equals("") || textI.getText().equals("")){
                int i = tbC.getSelectedRow();
                Cliente.cliente.get(tbC.getSelectedRow()).setNome("");
                ((DefaultTableModel) tbC.getModel()).removeRow(tbC.getSelectedRow());
                cliente.remove(i);
            }
            else
                JOptionPane.showMessageDialog(null,"Atualize a edição antes de apagar.",null,JOptionPane.INFORMATION_MESSAGE);
        }   
    }//GEN-LAST:event_apagaCActionPerformed

    private void voltaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltaCActionPerformed
        telaPrincipal volta = new telaPrincipal(this);
        volta.setVisible(true);
        volta.setResizable(false);
        this.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_voltaCActionPerformed

    private void editaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editaCActionPerformed
        int i;
        i = tbC.getSelectedRow();
        
        if(i == -1)
            JOptionPane.showMessageDialog(null,"Selecione uma linha para edição.",null,JOptionPane.INFORMATION_MESSAGE);
        else{
            textoN.setText(cliente.get(i).getNome());
            textC.setText(cliente.get(i).getDocumento());
            textE.setText(cliente.get(i).getEndereco());
            textT.setText(cliente.get(i).getContato());
            textI.setText(cliente.get(i).getIdade());
        }
    }//GEN-LAST:event_editaCActionPerformed

    private void atualizaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaCActionPerformed
        
        if(textoN.getText().equals("") || textT.getText().equals("") || textE.getText().equals("") || textC.getText().equals("") || textI.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Selecione uma linha e clique em \"Editar\" antes de atualizar.",null,JOptionPane.INFORMATION_MESSAGE);
        else{
            String nome = this.textoN.getText().trim();
            String tel = this.textT.getText().trim();
            String end = this.textE.getText().trim();
            String cpf = this.textC.getText().trim();
            String idade = this.textI.getText().trim();
            
            int z = tbC.getSelectedRow();
            cliente.remove(z);
            Cliente cli = new Cliente (nome, cpf, tel, end, idade);
            cliente.add(cli);
                       
            ((DefaultTableModel) tbC.getModel()).removeRow(tbC.getSelectedRow());
            DefaultTableModel val = (DefaultTableModel) tbC.getModel();
            val.addRow(new String[]{nome, tel, cpf, end, idade});
            
            
            textoN.setText("");
            textC.setText("");
            textE.setText("");
            textT.setText("");
            textI.setText("");
                 
            textoN.requestFocus();
        }
    }//GEN-LAST:event_atualizaCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apagaC;
    private javax.swing.JButton atualizaC;
    private javax.swing.JButton cadastraC;
    private javax.swing.JButton editaC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable jTable1;
    public javax.swing.JTable tbC;
    private javax.swing.JTextField textC;
    private javax.swing.JTextField textE;
    private javax.swing.JTextField textI;
    private javax.swing.JTextField textT;
    private javax.swing.JTextField textoN;
    private javax.swing.JButton voltaC;
    // End of variables declaration//GEN-END:variables
}
