/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mercado.telas;

import com.mycompany.mercado.controle.EventoFornecedor;
import com.mycompany.mercado.mercadoClasses.Estoque;
import com.mycompany.mercado.mercadoClasses.Fornecedor;
import static com.mycompany.mercado.mercadoClasses.Fornecedor.fornecedor;
import com.mycompany.mercado.mercadoClasses.Pessoa;
import javax.swing.JFormattedTextField;
import javax.swing.text.MaskFormatter;
import java.text.ParseException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gusta
 */
public class cadastroFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form cadastroFornecedor
     */
    JFrame telaAnterior;
    public cadastroFornecedor(){
        initComponents();
        this.addWindowListener(new EventoFornecedor(this));
    }
    public cadastroFornecedor(JFrame telaAnterior){
        this();
        this.telaAnterior = telaAnterior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        telFor = new javax.swing.JTextField();
        endFor = new javax.swing.JTextField();
        nomeFor = new javax.swing.JTextField();
        cnpjFor = new javax.swing.JTextField();
        try {
            cnpjFor = new JFormattedTextField(new MaskFormatter("##.###.###/0001-##"));
        } catch (ParseException e) {}
        cadastraFor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFor = new javax.swing.JTable();
        editaFor = new javax.swing.JButton();
        apagaFor = new javax.swing.JButton();
        voltaFor = new javax.swing.JButton();
        atualiza = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Fornecedor");

        jLabel2.setText("Nome:");

        jLabel3.setText("CNPJ:");

        jLabel4.setText("Telefone:");

        jLabel5.setText("Endereço:");

        cadastraFor.setText("Cadastrar");
        cadastraFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastraForActionPerformed(evt);
            }
        });

        tableFor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Telefone", "CNPJ", "Endereço"
            }
        ));
        jScrollPane1.setViewportView(tableFor);

        editaFor.setText("Editar");
        editaFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editaForActionPerformed(evt);
            }
        });

        apagaFor.setText("Apagar");
        apagaFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagaForActionPerformed(evt);
            }
        });

        voltaFor.setText("Voltar");
        voltaFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltaForActionPerformed(evt);
            }
        });

        atualiza.setText("Atualizar");
        atualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomeFor)
                            .addComponent(cnpjFor, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endFor, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telFor, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(atualiza)
                        .addGap(26, 26, 26)
                        .addComponent(apagaFor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltaFor))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editaFor))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(cadastraFor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(telFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(endFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnpjFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cadastraFor)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editaFor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atualiza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(voltaFor)
                        .addComponent(apagaFor)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(742, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastraForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraForActionPerformed
        if(nomeFor.getText().equals("") || telFor.getText().equals("") || endFor.getText().equals("") || cnpjFor.getText().equals(""))
          JOptionPane.showMessageDialog(null,"Preencha todos os campos.",null,JOptionPane.ERROR_MESSAGE);  
        else{
            String nome = this.nomeFor.getText().trim();
            String tel = this.telFor.getText().trim();
            String end = this.endFor.getText().trim();
            String cnpj = this.cnpjFor.getText().trim();
        
            if(Pessoa.verificaContato(tel)==true){
                 DefaultTableModel val = (DefaultTableModel) tableFor.getModel();
                 val.addRow(new String[]{nome, tel, cnpj, end});
                 telFor.setText("");
                 cnpjFor.setText("");
                 endFor.setText("");
                 nomeFor.setText("");
                 
                 nomeFor.requestFocus();
                 
            Fornecedor forn = new Fornecedor (nome, cnpj, tel, end);
            fornecedor.add(forn);
            }else{
                JOptionPane.showMessageDialog(null,"Digite apenas números no telefone.",null,JOptionPane.ERROR_MESSAGE);
                telFor.setText("");
        
                telFor.requestFocus();
            }
        }
    }//GEN-LAST:event_cadastraForActionPerformed

    
    private void apagaForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagaForActionPerformed
        if(tableFor.getSelectedRow()== -1)
            JOptionPane.showMessageDialog(null,"Selecione uma linha antes de apagar.",null,JOptionPane.INFORMATION_MESSAGE);
        else{
            if(nomeFor.getText().equals("") || telFor.getText().equals("") || cnpjFor.getText().equals("") || endFor.getText().equals("")){
                int i = tableFor.getSelectedRow();
                Fornecedor.fornecedor.get(tableFor.getSelectedRow()).setNome("");
                ((DefaultTableModel) tableFor.getModel()).removeRow(tableFor.getSelectedRow());
                fornecedor.remove(i);
            }
            else
                JOptionPane.showMessageDialog(null,"Atualize a edição antes de apagar.",null,JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_apagaForActionPerformed

    private void voltaForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltaForActionPerformed
        telaPrincipal volta = new telaPrincipal(this);
        volta.setVisible(true);
        volta.setResizable(false);
        this.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_voltaForActionPerformed

    private void editaForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editaForActionPerformed
        int i;
        i = tableFor.getSelectedRow();
              
        if(i == -1)
            JOptionPane.showMessageDialog(null,"Selecione uma linha para edição.",null,JOptionPane.INFORMATION_MESSAGE);
        else{
            cnpjFor.setText(fornecedor.get(i).getDocumento());
            nomeFor.setText(fornecedor.get(i).getNome());
            endFor.setText(fornecedor.get(i).getEndereco());
            telFor.setText(fornecedor.get(i).getContato());
        }
    }//GEN-LAST:event_editaForActionPerformed

    private void atualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaActionPerformed

        if(nomeFor.getText().equals("") || telFor.getText().equals("") || endFor.getText().equals("") || cnpjFor.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Selecione uma linha e clique em \"Editar\" antes de atualizar.",null,JOptionPane.INFORMATION_MESSAGE);
        else{
            String nome = this.nomeFor.getText().trim();
            String tel = this.telFor.getText().trim();
            String end = this.endFor.getText().trim();
            String cnpj = this.cnpjFor.getText().trim();
            
            int z = tableFor.getSelectedRow();
            fornecedor.remove(z);
            Fornecedor forn = new Fornecedor (nome, cnpj, tel, end);
            fornecedor.add(forn);
            
            ((DefaultTableModel) tableFor.getModel()).removeRow(tableFor.getSelectedRow());
            DefaultTableModel val = (DefaultTableModel) tableFor.getModel();
            val.addRow(new String[]{nome, tel, cnpj, end});            
            
            telFor.setText("");
            cnpjFor.setText("");
            endFor.setText("");
            nomeFor.setText("");
                 
            nomeFor.requestFocus();
        }
        
    }//GEN-LAST:event_atualizaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apagaFor;
    private javax.swing.JButton atualiza;
    private javax.swing.JButton cadastraFor;
    private javax.swing.JTextField cnpjFor;
    private javax.swing.JButton editaFor;
    private javax.swing.JTextField endFor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nomeFor;
    public javax.swing.JTable tableFor;
    private javax.swing.JTextField telFor;
    private javax.swing.JButton voltaFor;
    // End of variables declaration//GEN-END:variables
}
