/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mercado.telas;

import com.mycompany.mercado.controle.EventoFuncionarios;
import com.mycompany.mercado.mercadoClasses.Funcionario;
import static com.mycompany.mercado.mercadoClasses.Funcionario.func;
import java.text.ParseException;
import com.mycompany.mercado.mercadoClasses.Pessoa;
import com.mycompany.mercado.telas.telaVenda;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author gusta
 */
public class cadastroFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form cadastroFuncionario
     */


    JFrame telaAnterior;
    
    public cadastroFuncionario() {
        initComponents();
        this.addWindowListener(new EventoFuncionarios(this));
    }

    public cadastroFuncionario(JFrame telaAnterior){
        this();
        this.telaAnterior = telaAnterior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nomeFuncionario = new javax.swing.JTextField();
        cpfFuncionario = new javax.swing.JTextField();
        try {
            cpfFuncionario = new JFormattedTextField(new MaskFormatter("###.###.###-##"));
        } catch (ParseException e) {}
        idFuncionario = new javax.swing.JTextField();
        endFuncionario = new javax.swing.JTextField();
        telFuncionario = new javax.swing.JTextField();
        cargoFuncionario = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cFuncionario = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        editaFunc = new javax.swing.JButton();
        apagaFunc = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableFunc = new javax.swing.JTable();
        atualiza = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Funcionário");

        cargoFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionario", "Gerente" }));

        jLabel2.setText("Nome:");

        jLabel3.setText("ID:");

        jLabel4.setText("CPF:");

        jLabel5.setText("Endereço:");

        jLabel6.setText("Cargo:");

        jLabel7.setText("Telefone:");

        cFuncionario.setText("Cadastrar");
        cFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cFuncionarioActionPerformed(evt);
            }
        });

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        editaFunc.setText("Editar");
        editaFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editaFuncActionPerformed(evt);
            }
        });

        apagaFunc.setText("Apagar");
        apagaFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagaFuncActionPerformed(evt);
            }
        });

        tableFunc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "ID", "Endereço", "Telefone", "Cargo"
            }
        ));
        jScrollPane2.setViewportView(tableFunc);

        atualiza.setText("Atualiza");
        atualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(atualiza)
                                .addGap(18, 18, 18)
                                .addComponent(apagaFunc)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nomeFuncionario)
                            .addComponent(telFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(idFuncionario, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton2)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(editaFunc))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(cFuncionario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(endFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(cFuncionario)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editaFunc)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apagaFunc)
                    .addComponent(jButton2)
                    .addComponent(atualiza))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(743, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cFuncionarioActionPerformed

        String nome = this.nomeFuncionario.getText().trim();
        String id = this.idFuncionario.getText().trim();
        String cpf = this.cpfFuncionario.getText().trim();
        String end = this.endFuncionario.getText().trim();
        String tel = this.telFuncionario.getText().trim();
        String cargo = (String) cargoFuncionario.getSelectedItem();
        
        if(Pessoa.verificaContato(tel)==true){
        DefaultTableModel val = (DefaultTableModel) tableFunc.getModel();
        val.addRow(new String[]{nome, cpf, id, end, tel, cargo});
        
        nomeFuncionario.setText("");
        idFuncionario.setText("");
        cpfFuncionario.setText("");
        telFuncionario.setText("");
        endFuncionario.setText("");
        
        nomeFuncionario.requestFocus();
        
        Funcionario funcionario = new Funcionario (id, cargo, nome, cpf, tel, end);
        func.add(funcionario);

        }
        else{
            JOptionPane.showMessageDialog(null,"Digite apenas números no telefone.",null,JOptionPane.ERROR_MESSAGE);
            telFuncionario.setText("");
            telFuncionario.requestFocus();
        }
    }//GEN-LAST:event_cFuncionarioActionPerformed

    private void apagaFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagaFuncActionPerformed
        if(tableFunc.getSelectedRow() == -1)
            JOptionPane.showMessageDialog(null,"Selecione uma linha antes de apagar.",null,JOptionPane.INFORMATION_MESSAGE);
        else{
            if(nomeFuncionario.getText().equals("") || endFuncionario.getText().equals("") || telFuncionario.getText().equals("") || cpfFuncionario.getText().equals("") || idFuncionario.getText().equals("")){  
            int i = tableFunc.getSelectedRow();
            Funcionario.func.get(tableFunc.getSelectedRow()).setNome("");
            ((DefaultTableModel) tableFunc.getModel()).removeRow(tableFunc.getSelectedRow());
            func.remove(i);}
            else
                JOptionPane.showMessageDialog(null,"Atualize a edição antes de apagar.",null,JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_apagaFuncActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        telaPrincipal volta = new telaPrincipal(this);
        volta.setVisible(true);
        volta.setResizable(false);
        this.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void editaFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editaFuncActionPerformed
        int i;
        i = tableFunc.getSelectedRow();
        if(i == -1)
            JOptionPane.showMessageDialog(null,"Selecione uma linha para edição.",null,JOptionPane.INFORMATION_MESSAGE);
        else{
            nomeFuncionario.setText(func.get(i).getNome());
            cpfFuncionario.setText(func.get(i).getDocumento());
            endFuncionario.setText(func.get(i).getEndereco());
            telFuncionario.setText(func.get(i).getContato());
            idFuncionario.setText(func.get(i).getId());
            cargoFuncionario.setSelectedItem(func.get(i).getCargo());
        }
    }//GEN-LAST:event_editaFuncActionPerformed

    private void atualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaActionPerformed
        if(nomeFuncionario.getText().equals("") || telFuncionario.getText().equals("") || endFuncionario.getText().equals("") || cpfFuncionario.getText().equals("") || idFuncionario.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Selecione uma linha e clique em \"Editar\" antes de atualizar.",null,JOptionPane.INFORMATION_MESSAGE);
        else{
            String nome = this.nomeFuncionario.getText().trim();
            String tel = this.telFuncionario.getText().trim();
            String end = this.endFuncionario.getText().trim();
            String cpf = this.cpfFuncionario.getText().trim();
            String id = this.idFuncionario.getText().trim();
            String cargo = this.cargoFuncionario.getSelectedItem().toString().trim();
            
            int z = tableFunc.getSelectedRow();
            func.remove(z);
            Funcionario funcionario = new Funcionario (id, cargo, nome, cpf, tel, end);
            func.add(funcionario);
            
            ((DefaultTableModel) tableFunc.getModel()).removeRow(tableFunc.getSelectedRow());
            DefaultTableModel val = (DefaultTableModel) tableFunc.getModel();
            val.addRow(new String[]{nome, cpf, id, end, tel, cargo});
            
            telFuncionario.setText("");
            cpfFuncionario.setText("");
            endFuncionario.setText("");
            nomeFuncionario.setText("");
            idFuncionario.setText("");
            cargoFuncionario.setSelectedIndex(0);
                 
            nomeFuncionario.requestFocus();
        }
    }//GEN-LAST:event_atualizaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apagaFunc;
    private javax.swing.JButton atualiza;
    private javax.swing.JButton cFuncionario;
    private javax.swing.JComboBox<String> cargoFuncionario;
    private javax.swing.JTextField cpfFuncionario;
    private javax.swing.JButton editaFunc;
    private javax.swing.JTextField endFuncionario;
    private javax.swing.JTextField idFuncionario;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nomeFuncionario;
    public javax.swing.JTable tableFunc;
    private javax.swing.JTextField telFuncionario;
    // End of variables declaration//GEN-END:variables
}
