/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mercado.telas;

import com.mycompany.mercado.mercadoClasses.Estoque;
import static com.mycompany.mercado.mercadoClasses.Estoque.estoque;
import com.mycompany.mercado.mercadoClasses.Produto;
import com.mycompany.mercado.utils.Arquivo;
import com.mycompany.mercado.utils.JSON;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gusta
 */
public class telaVenda extends javax.swing.JFrame {

    /**
     * Creates new form telaVenda
     */
    JFrame telaAnterior;
    boolean botaoAtivo = true;
    private static float precoT=0;
    public static List<Produto> carrinhoList = new ArrayList<>();
    
    public telaVenda() {
        initComponents();
    }
    public telaVenda(JFrame telaAnterior){
        this();
        this.telaAnterior = telaAnterior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProd = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCarrinho = new javax.swing.JTable();
        adicionaCarrinho = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        finaliza = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cancelaProdutos = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        pDisp = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        precoTotal = new javax.swing.JTextField();
        verPreco = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Disponíveis");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Venda");

        tbProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produtos", "Preço", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(tbProd);

        tbCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produtos", "Preço", "Quantidade"
            }
        ));
        jScrollPane2.setViewportView(tbCarrinho);

        adicionaCarrinho.setText("Adicionar");
        adicionaCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionaCarrinhoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Carrinho");

        finaliza.setText("Finalizar Compra");
        finaliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Preço Total:");

        cancelaProdutos.setText("Cancelar");
        cancelaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelaProdutosActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Forma de Pagamento:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "À Vista", "Parcelado" }));

        pDisp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pDisp.setText("Ver Produtos Disponíveis");
        pDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pDispActionPerformed(evt);
            }
        });

        cancelar.setText("Voltar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        precoTotal.setEditable(false);

        verPreco.setText("Ver Preço Total");
        verPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPrecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(verPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cancelaProdutos)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(adicionaCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(finaliza, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cancelar))
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(41, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(pDisp)
                        .addGap(275, 275, 275)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pDisp)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(adicionaCarrinho)))
                .addGap(14, 14, 14)
                .addComponent(cancelaProdutos)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verPreco)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar)
                    .addComponent(finaliza))
                .addGap(30, 30, 30))
        );

        setSize(new java.awt.Dimension(742, 533));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void pDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pDispActionPerformed
        if(tbProd.getModel().getRowCount() > 0)
            JOptionPane.showMessageDialog(null,"O estoque já está sendo mostrado.",null,JOptionPane.INFORMATION_MESSAGE);
        else{
        String lerArquivo = Arquivo.lerArquivo("dados.json");
        if(lerArquivo.length() != 0){ 
        Estoque.estoque = JSON.toProdutos(lerArquivo);
        }
        
        if(Estoque.estoque.size() > 0){
        for(int i = 0; i < Estoque.estoque.size(); i++){
            int id = Estoque.estoque.get(i).getId_produto();
            String nome =  Estoque.estoque.get(i).getNome();
            String marca =  Estoque.estoque.get(i).getMarca();
            String validade =  Estoque.estoque.get(i).getValidade();
            String preco = String.valueOf( Estoque.estoque.get(i).getPreco());
            String codigo_barras = String.valueOf( Estoque.estoque.get(i).getCodigo_barras());
            int valor = Estoque.estoque.get(i).getQuantidade();

            if(nome.length() > 0){
                DefaultTableModel val = (DefaultTableModel) tbProd.getModel();
                val.addRow(new String[]{nome, preco, String.valueOf (valor)});
            }
        }
        }
        carrinhoList=estoque;
        }
    }//GEN-LAST:event_pDispActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        telaPrincipal volta = new telaPrincipal(this);
        volta.setVisible(true);
        volta.setResizable(false);
        this.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void finalizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizaActionPerformed
        estoque=carrinhoList;
        String toJSON = JSON.toJSON(Estoque.estoque);
        Arquivo.escreverArquivo("dados.json", toJSON);
        JOptionPane.showMessageDialog(null, "Obrigado por comprar com a MercadOO.");
        precoT=0;
        telaPrincipal volta = new telaPrincipal(this);
        volta.setVisible(true);
        volta.setResizable(false);
        this.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_finalizaActionPerformed

    private void adicionaCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionaCarrinhoActionPerformed
        if(tbProd.getSelectedRow()== -1)
            JOptionPane.showMessageDialog(null,"Selecione uma linha antes de adicionar ao carriho.",null,JOptionPane.INFORMATION_MESSAGE);
          else{
            int aux = tbProd.getSelectedRow()+1;
            String quantidade = JOptionPane.showInputDialog("Digite a quantidade desejada desse produto:");
            int quant = Integer.parseInt(quantidade);
            if(quant>carrinhoList.get(aux).getQuantidade() || quant==0)
            {
                JOptionPane.showMessageDialog(null,"Revise a quantidade selecionada.",null,JOptionPane.ERROR_MESSAGE);
            }
              else{
                String nome =  carrinhoList.get(aux).getNome();
                String preco = String.valueOf( carrinhoList.get(aux).getPreco());
                int valor = carrinhoList.get(aux).getQuantidade();
   
                  if(valor==0){
                     JOptionPane.showMessageDialog(null,"Este produto acabou, estamos esperando abastecimento. Desculpe-nos pelo incômodo.",null,JOptionPane.INFORMATION_MESSAGE);
                  }
                       else{
                         DefaultTableModel val = (DefaultTableModel) tbCarrinho.getModel();
                         val.addRow(new String[]{nome, preco, quantidade});
                         int quantEst = estoque.get(aux).getQuantidade();
                         float precoFloat = Float.parseFloat(preco);
                         precoT += quant*precoFloat;
                         
                         carrinhoList.get(aux).setQuantidade(quantEst-quant);
                       }
              }
          }
    }//GEN-LAST:event_adicionaCarrinhoActionPerformed

    private void cancelaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelaProdutosActionPerformed
        while (tbCarrinho.getModel().getRowCount() > 0) {
        ((DefaultTableModel)tbCarrinho.getModel()).removeRow(0);
        }
        carrinhoList=estoque;
        precoT=0;
        precoTotal.setText("");
    }//GEN-LAST:event_cancelaProdutosActionPerformed

    private void verPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPrecoActionPerformed
        if(tbCarrinho.getRowCount()==0)
            JOptionPane.showMessageDialog(null,"Adicione algo ao carrinho antes.",null,JOptionPane.INFORMATION_MESSAGE);
        else{
            precoTotal.setText("R$" + precoT + "0");
        }
    }//GEN-LAST:event_verPrecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaVenda().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionaCarrinho;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cancelaProdutos;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton finaliza;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton pDisp;
    private javax.swing.JTextField precoTotal;
    private javax.swing.JTable tbCarrinho;
    private javax.swing.JTable tbProd;
    private javax.swing.JButton verPreco;
    // End of variables declaration//GEN-END:variables
}
