/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mercado.telas;

import javax.swing.JFrame;

/**
 *
 * @author gusta
 */
public class telaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipal
     */
    JFrame telaAnterior;
    public telaPrincipal() {
        initComponents();
    }
    public telaPrincipal(JFrame telaAnterior){
        this();
        this.telaAnterior = telaAnterior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuCliente = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        menuFuncionario = new javax.swing.JCheckBoxMenuItem();
        menuFornecedor = new javax.swing.JCheckBoxMenuItem();
        menuProduto = new javax.swing.JCheckBoxMenuItem();
        menuV = new javax.swing.JMenu();
        menuVenda = new javax.swing.JMenuItem();
        menuAbastecimento = new javax.swing.JMenu();
        abastecimentoM = new javax.swing.JMenuItem();
        menuEstoque = new javax.swing.JMenu();
        estoqueM = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("File");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("jMenu5");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("M°°");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(115, 115, 115))
        );

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        menuCliente.setText("Cadastrar");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Cliente");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        menuCliente.add(jCheckBoxMenuItem1);

        menuFuncionario.setSelected(true);
        menuFuncionario.setText("Funcionário");
        menuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncionarioActionPerformed(evt);
            }
        });
        menuCliente.add(menuFuncionario);

        menuFornecedor.setSelected(true);
        menuFornecedor.setText("Fornecedor");
        menuFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFornecedorActionPerformed(evt);
            }
        });
        menuCliente.add(menuFornecedor);

        menuProduto.setSelected(true);
        menuProduto.setText("Produto");
        menuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdutoActionPerformed(evt);
            }
        });
        menuCliente.add(menuProduto);

        jMenuBar2.add(menuCliente);

        menuV.setText("Venda");
        menuV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVActionPerformed(evt);
            }
        });

        menuVenda.setText("Venda");
        menuVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendaActionPerformed(evt);
            }
        });
        menuV.add(menuVenda);

        jMenuBar2.add(menuV);

        menuAbastecimento.setText("Abastecimento");
        menuAbastecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbastecimentoActionPerformed(evt);
            }
        });

        abastecimentoM.setText("Abastecimento");
        abastecimentoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoMActionPerformed(evt);
            }
        });
        menuAbastecimento.add(abastecimentoM);

        jMenuBar2.add(menuAbastecimento);

        menuEstoque.setText("Estoque");
        menuEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEstoqueActionPerformed(evt);
            }
        });

        estoqueM.setText("Estoque");
        estoqueM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estoqueMActionPerformed(evt);
            }
        });
        menuEstoque.add(estoqueM);

        jMenuBar2.add(menuEstoque);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jButton1)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton1)
                .addGap(56, 56, 56))
        );

        setSize(new java.awt.Dimension(742, 546));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        cadastroCliente irParaC = new cadastroCliente(this);
        irParaC.setVisible(true);
        irParaC.setResizable(false);
        this.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_menuClienteActionPerformed

    private void menuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionarioActionPerformed
        cadastroFuncionario irParaFunc = new cadastroFuncionario(this);
        irParaFunc.setVisible(true);
        irParaFunc.setResizable(false);
        this.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_menuFuncionarioActionPerformed

    private void menuFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFornecedorActionPerformed
        cadastroFornecedor irParaFor = new cadastroFornecedor(this);
        irParaFor.setVisible(true);
        irParaFor.setResizable(false);
        this.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_menuFornecedorActionPerformed

    private void menuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdutoActionPerformed
        cadastroProdutos irParaProd = new cadastroProdutos(this);
        irParaProd.setVisible(true);
        irParaProd.setResizable(false);
        this.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_menuProdutoActionPerformed

    private void menuVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVActionPerformed
        telaVenda x = new telaVenda(this);
        x.setVisible(true);
        x.setResizable(false);
        this.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_menuVActionPerformed

    private void menuAbastecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbastecimentoActionPerformed
        abastecimentoEstoque irParaAbastecimentoEstoque = new abastecimentoEstoque(this);
        irParaAbastecimentoEstoque.setVisible(true);
        irParaAbastecimentoEstoque.setResizable(false);
        this.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_menuAbastecimentoActionPerformed

    private void menuEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEstoqueActionPerformed
        telaEstoque irParaEstoque = new telaEstoque(this);
        irParaEstoque.setVisible(true);
        irParaEstoque.setResizable(false);
        this.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_menuEstoqueActionPerformed

    private void menuVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendaActionPerformed
        telaVenda ir = new telaVenda(this);
        ir.setVisible(true);
        ir.setResizable(false);
        this.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_menuVendaActionPerformed

    private void abastecimentoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoMActionPerformed
        abastecimentoEstoque irA = new abastecimentoEstoque(this);
        irA.setVisible(true);
        irA.setResizable(false);
        this.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_abastecimentoMActionPerformed

    private void estoqueMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoqueMActionPerformed
        telaEstoque irE = new telaEstoque(this);
        irE.setVisible(true);
        irE.setResizable(false);
        this.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_estoqueMActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        cadastroCliente irC = new cadastroCliente(this);
        irC.setVisible(true);
        irC.setResizable(false);
        this.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abastecimentoM;
    private javax.swing.JMenuItem estoqueM;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuAbastecimento;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuEstoque;
    private javax.swing.JCheckBoxMenuItem menuFornecedor;
    private javax.swing.JCheckBoxMenuItem menuFuncionario;
    private javax.swing.JCheckBoxMenuItem menuProduto;
    private javax.swing.JMenu menuV;
    private javax.swing.JMenuItem menuVenda;
    // End of variables declaration//GEN-END:variables
}
